# Generated by Django 3.1.7 on 2021-03-23 20:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('write_list', '0002_auto_20210323_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
