# Generated by Django 3.1.7 on 2021-03-23 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('write_list', '0004_auto_20210323_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='updated_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
