# Generated by Django 3.1.7 on 2021-04-09 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('write_list', '0010_auto_20210401_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='created',
            field=models.DateTimeField(),
        ),
    ]
