# Generated by Django 3.1.7 on 2021-04-23 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('write_list', '0013_auto_20210423_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joint',
            name='joint_id',
            field=models.DecimalField(decimal_places=0, max_digits=20),
        ),
    ]
